name: deploy

on:
  push:
    tags:
      - "v*"

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Build and Check Package
      uses: hynek/build-and-inspect-python-package@v2.14

    - name: Download Package
      uses: actions/download-artifact@v6
      with:
        name: Packages
        path: dist

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_token }}
